---
title: "Relationship Between Crime Rate , Gross Domastic Product and Unemployment rate in Taiwan"
author: "Christine Hsieh, May Huang, Yi-Fang Lo"
date: "7/22/2019"
output: html_document
---
# Objective: There are 
# Data about Crimes committed in Taiwan
First import the data about crimes in Taiwan
[source]()
Chinese characters were removced to avoid encoding and compatibility issue

```{r warning=FALSE,message=FALSE} 
rm(list=ls())
library(readr)
library(tidyverse )

library(dplyr)
```


```{r}
GDP <- read_csv("https://raw.githubusercontent.com/Vladislav292/2019summer-datasciece/master/GDP.csv", )
head(GDP)
```



```{r}
edu <- read_csv("https://raw.githubusercontent.com/ChristineHsieh1231/mii/master/Educational%20Attainment.csv", 
     col_types = cols(X10 = col_number(), 
         X11 = col_number(), X12 = col_number(), 
         X13 = col_number(), X14 = col_number(), 
         X15 = col_number(), X16 = col_number(), 
         X17 = col_number(), X18 = col_number(), 
         X19 = col_number(), X2 = col_number(), 
         X20 = col_number(), X21 = col_number(), 
         X22 = col_number(), X23 = col_number(), 
         X24 = col_number(), X25 = col_number(), 
         X26 = col_number(), X27 = col_number(), 
         X28 = col_number(), X3 = col_number(), 
         X4 = col_number(), X5 = col_number(), 
         X6 = col_number(), X7 = col_number(), 
         X8 = col_number(), X9 = col_number()))
edu = filter(edu, Year<2017)
edu = filter(edu, Year>1996)
edu = edu %>%
  rename(
    year = Year,
    t = X2,
    m = X3,
    f = X4,
    t0 = X5,
    m0 = X6,
    f0 = X7,
    s = X8,
    ms = X9,
    fs = X10,
    t1 = X11,
    m1 = X12,
    f1 = X13,
    t2 = X14,
    m2 = X15,
    f2 = X16,
    t3 = X17, 
    m3 = X18,
    f3 = X19,
    t4 = X20,
    m4 = X21,
    f4 = X22,
    t5 = X23,
    m5 = X24,
    f5 = X25,
    t8 = X26,
    m8 = X27,
    f8 = X28
    
  )
    
   
```


```{r warning=FALSE,message=FALSE}
data_merged <-merge(edu, GDP,by="year")
head(data_merged)
```





```{r}
ggplot(data = data_merged)+
geom_line(mapping=aes(x=year,y=di,group=1))+geom_point(mapping = aes(x=year,y=di))
```

```{r}
ggplot(data = data_merged)+
geom_line(mapping=aes(x=year,y=t,group=1))+geom_point(mapping = aes(x=year,y=t))
```


```{r}
ggplot(data = data_merged)+
geom_line(mapping=aes(x=di,y=t,group=1))+geom_point(mapping = aes(x=di,y=t))
```



```{r}
edu0 = edu %>% select(year,t0,m0,f0) %>% 
    mutate(class = "illiterate") %>% rename(t=t0, m=m0,f=f0)
edu1 = edu %>% select(year,t1,m1,f1) %>%
    mutate(class = "primary")%>% rename(t=t1, m=m1,f=f1)
edu2 = edu %>% select(year,t2,m2,f2) %>%
    mutate(class = "junior")%>% rename(t=t2, m=m2,f=f2)
edu3 = edu %>% select(year,t3,m3,f3) %>%
    mutate(class = "senior")%>% rename(t=t3, m=m3,f=f3)
edu4 = edu %>% select(year,t4,m4,f4) %>%
    mutate(class = "undergrad")%>% rename(t=t4, m=m4,f=f4)
edu5 = edu %>% select(year,t5,m5,f5) %>%
    mutate(class = "grad")%>% rename(t=t5, m=m5,f=f5)
edus = edu %>% select(year,s,ms,fs) %>%
    mutate(class = "self")%>% rename(t=s, m=ms,f=fs)
edu8 = edu %>% select(year,t8,m8,f8) %>%
    mutate(class = "other")%>% rename(t=t8, m=m8,f=f8)
edue = rbind(edu0,edu1,edu2,edu3,edu4,edu5,edus,edu8)
edue$class=factor(edue$class,levels = c("grad","undergrad","senior","junior","primary","self","illiterate","other" ), ordered = TRUE )
head(edue)
```

```{r}
ggplot(data = edue,aes(x = year, y = t ,color=class ,group = class)) +
  geom_line()+
  geom_point()
```


```{r}
gender<-edu %>%
  select(year,t,m,f) %>% 
    mutate(fp = f / t, mp = m / t)
gendera= gender %>% select(year,fp)%>% mutate(gender="female")%>% rename(p=fp)
genderb= gender %>% select(year,mp)%>% mutate(gender="male")%>% rename(p=mp)
gender= rbind(gendera,genderb)

ggplot(data = gender,aes(x=year,y=p,group=gender,color=gender))+
geom_line()+
geom_point()


```
```{r}
sigma=data.frame(colSums(edu[,-1]))

```


```{r}

edumale = edue %>% select(year,m,t,class) %>% 
    mutate(gender = "male") %>% rename(count = m)
edufemale = edue %>% select(year,f,t,class) %>%
    mutate(gender = "female") %>%rename(count = f)
edugen = rbind(edumale,edufemale)
edugen=edugen%>% mutate(p=count/t)
head(edugen)
```

```{r}
uneply=read.csv("https://raw.githubusercontent.com/Vladislav292/finalproj/master/uneply.csv")
plot2 = merge(edu,uneply,by="year")
ggplot(data=plot2)+
geom_smooth(mapping=aes(x=total,y=t))+
geom_point(mapping =aes(x=total,y=t))
```

```{r}
ggplot(data=plot2)+
geom_smooth(mapping=aes(x=male,y=m))+
geom_point(mapping =aes(x=male,y=m))
```


```{r}
ggplot(data=plot2)+
geom_smooth(mapping=aes(x=female,y=f),model=lm)+
geom_point(mapping =aes(x=female,y=f))
```
```{r}
cor(data_merged$di,data_merged$t)
cor(plot2$total,data_merged$t)
cor(plot2$male,plot2$m)
cor(plot2$female,plot2$f)
cor(data_merged$year,data_merged$t)
```

```{r}
CRIMECLASS<-uneply%>%select(year,primary,junior,seniorv,senior,vocational,juniorca,junior.1,universitya)

CRIMECLASS  
```


```{r}
primary = CRIMECLASS %>% select(year,primary) %>% 
    mutate(class = "primary") %>% rename(CL=primary)

junior = CRIMECLASS%>%select(year,junior)%>%
  mutate(class="junior")%>% rename(CL=junior)
seniorv = CRIMECLASS%>%select(year,seniorv)%>%
  mutate(class="seniorv")%>% rename(CL=seniorv)
senior = CRIMECLASS%>%select(year,senior)%>%
  mutate(class="senior")%>% rename(CL=senior)
vocational = CRIMECLASS%>%select(year,vocational)%>%
  mutate(class="vocational")%>% rename(CL=vocational)
juniorca = CRIMECLASS%>%select(year,juniorca)%>%
  mutate(class="juniorca")%>% rename(CL=juniorca)
junior.1 = CRIMECLASS%>%select(year,junior.1)%>%
  mutate(class="junior.1")%>% rename(CL=junior.1)
universitya = CRIMECLASS%>%select(year,universitya)%>%
  mutate(class="universitya")%>% rename(CL=universitya)

CRI1 = rbind(primary,seniorv,senior,vocational,juniorca,junior.1,universitya)

head(CRI1)

```

```{r}
ggplot(data = CRI1,aes(x = year, y = CL ,color=class ,group = class)) +
  geom_line()+
  geom_point()
```

```{r}
cor(edu3$t,seniorv$CL)
cor(edu2$t,junior$CL)
```
  
